// Mocks generated by Mockito 5.4.6 from annotations
// in bus_ticketing_mobile/test/features/home/domain/usecases/home_usecases_mockito_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:bus_ticketing_mobile/core/error/failures.dart' as _i5;
import 'package:bus_ticketing_mobile/features/home/domain/entities/home_dashboard_entity.dart'
    as _i6;
import 'package:bus_ticketing_mobile/features/home/domain/entities/my_ticket_entity.dart'
    as _i7;
import 'package:bus_ticketing_mobile/features/home/domain/entities/settings_entity.dart'
    as _i8;
import 'package:bus_ticketing_mobile/features/home/domain/entities/ticket_option_entity.dart'
    as _i10;
import 'package:bus_ticketing_mobile/features/home/domain/entities/trip_search_criteria_entity.dart'
    as _i11;
import 'package:bus_ticketing_mobile/features/home/domain/repositories/home_overview_repository.dart'
    as _i3;
import 'package:bus_ticketing_mobile/features/home/domain/repositories/ticket_search_repository.dart'
    as _i9;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HomeOverviewRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeOverviewRepository extends _i1.Mock
    implements _i3.HomeOverviewRepository {
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.HomeDashboardEntity>>
  getHomeDashboard() =>
      (super.noSuchMethod(
            Invocation.method(#getHomeDashboard, []),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i6.HomeDashboardEntity>
                >.value(
                  _FakeEither_0<_i5.Failure, _i6.HomeDashboardEntity>(
                    this,
                    Invocation.method(#getHomeDashboard, []),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i6.HomeDashboardEntity>
                >.value(
                  _FakeEither_0<_i5.Failure, _i6.HomeDashboardEntity>(
                    this,
                    Invocation.method(#getHomeDashboard, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.HomeDashboardEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.MyTicketEntity>>>
  getMyTickets() =>
      (super.noSuchMethod(
            Invocation.method(#getMyTickets, []),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i7.MyTicketEntity>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i7.MyTicketEntity>>(
                    this,
                    Invocation.method(#getMyTickets, []),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i7.MyTicketEntity>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i7.MyTicketEntity>>(
                    this,
                    Invocation.method(#getMyTickets, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i7.MyTicketEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.SettingsEntity>> getSettings() =>
      (super.noSuchMethod(
            Invocation.method(#getSettings, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i8.SettingsEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i8.SettingsEntity>(
                    this,
                    Invocation.method(#getSettings, []),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, _i8.SettingsEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i8.SettingsEntity>(
                    this,
                    Invocation.method(#getSettings, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i8.SettingsEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool?>> getDarkModePreference() =>
      (super.noSuchMethod(
            Invocation.method(#getDarkModePreference, []),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, bool?>>.value(
              _FakeEither_0<_i5.Failure, bool?>(
                this,
                Invocation.method(#getDarkModePreference, []),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, bool?>>.value(
                  _FakeEither_0<_i5.Failure, bool?>(
                    this,
                    Invocation.method(#getDarkModePreference, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, bool?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> setDarkModePreference(
    bool? enabled,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setDarkModePreference, [enabled]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#setDarkModePreference, [enabled]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, void>>.value(
                  _FakeEither_0<_i5.Failure, void>(
                    this,
                    Invocation.method(#setDarkModePreference, [enabled]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);
}

/// A class which mocks [TicketSearchRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTicketSearchRepository extends _i1.Mock
    implements _i9.TicketSearchRepository {
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i10.TicketOptionEntity>>>
  searchTickets(_i11.TripSearchCriteriaEntity? criteria) =>
      (super.noSuchMethod(
            Invocation.method(#searchTickets, [criteria]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i10.TicketOptionEntity>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i10.TicketOptionEntity>>(
                    this,
                    Invocation.method(#searchTickets, [criteria]),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i10.TicketOptionEntity>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i10.TicketOptionEntity>>(
                    this,
                    Invocation.method(#searchTickets, [criteria]),
                  ),
                ),
          )
          as _i4.Future<
            _i2.Either<_i5.Failure, List<_i10.TicketOptionEntity>>
          >);
}
