// Mocks generated by Mockito 5.4.6 from annotations
// in bus_ticketing_mobile/test/features/seat_selection/domain/usecases/seat_selection_usecases_mockito_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:bus_ticketing_mobile/core/error/failures.dart' as _i5;
import 'package:bus_ticketing_mobile/features/seat_selection/domain/entities/seat_entity.dart'
    as _i6;
import 'package:bus_ticketing_mobile/features/seat_selection/domain/repositories/seat_selection_repository.dart'
    as _i3;
import 'package:bus_ticketing_mobile/features/seat_selection/domain/usecases/book_ticket_usecase.dart'
    as _i7;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SeatSelectionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSeatSelectionRepository extends _i1.Mock
    implements _i3.SeatSelectionRepository {
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.SeatEntity>>> getSeatPlan(
    String? busId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSeatPlan, [busId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.SeatEntity>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.SeatEntity>>(
                    this,
                    Invocation.method(#getSeatPlan, [busId]),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.SeatEntity>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.SeatEntity>>(
                    this,
                    Invocation.method(#getSeatPlan, [busId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.SeatEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> bookTicket(
    _i7.BookTicketParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#bookTicket, [params]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#bookTicket, [params]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, void>>.value(
                  _FakeEither_0<_i5.Failure, void>(
                    this,
                    Invocation.method(#bookTicket, [params]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
