// Mocks generated by Mockito 5.4.6 from annotations
// in bus_ticketing_mobile/test/features/onboarding/domain/usecases/onboarding_usecases_mockito_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:bus_ticketing_mobile/core/error/failures.dart' as _i5;
import 'package:bus_ticketing_mobile/features/onboarding/domain/entities/onboarding_status_entity.dart'
    as _i6;
import 'package:bus_ticketing_mobile/features/onboarding/domain/repositories/onboarding_repository.dart'
    as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [OnboardingRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOnboardingRepository extends _i1.Mock
    implements _i3.OnboardingRepository {
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.OnboardingStatusEntity>>
  getOnboardingStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getOnboardingStatus, []),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i6.OnboardingStatusEntity>
                >.value(
                  _FakeEither_0<_i5.Failure, _i6.OnboardingStatusEntity>(
                    this,
                    Invocation.method(#getOnboardingStatus, []),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i6.OnboardingStatusEntity>
                >.value(
                  _FakeEither_0<_i5.Failure, _i6.OnboardingStatusEntity>(
                    this,
                    Invocation.method(#getOnboardingStatus, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.OnboardingStatusEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> setOnboardingCompleted(
    bool? isCompleted,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setOnboardingCompleted, [isCompleted]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#setOnboardingCompleted, [isCompleted]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, void>>.value(
                  _FakeEither_0<_i5.Failure, void>(
                    this,
                    Invocation.method(#setOnboardingCompleted, [isCompleted]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
